# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cpinas <cpinas@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/05/19 15:17:31 by cpinas            #+#    #+#              #
#    Updated: 2025/09/25 19:19:56 by cpinas           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# NAME        = libft.a
# CC          = gcc
# CFLAGS      = -Wall -Wextra -Werror
# AR          = ar rcs

# MAKEFLAGS   += -j$(shell nproc)

# SRC = ft_strlcpy.c ft_strlen.c ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c\
#  ft_isprint.c ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_strlcat.c\
#  ft_toupper.c ft_tolower.c ft_strchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c\
#  ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_strrchr.c ft_substr.c ft_strjoin.c\
#  ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c\
#  ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c lib/ft_printf.c lib/ft_putchar.c\
#  lib/ft_putstr.c lib/ft_putnbr.c lib/ft_itoahex.c lib/ft_strlenn.c lib/ft_strrevv.c\
#  lib/ft_toupperr.c lib/ft_strncpyy.c\
#  lib/ft_hex_specifier.c lib/ft_putnbr_unsigned.c

# BONUS_SRC = ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c\
#  ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

# OBJ         = $(SRC:.c=.o)
# BONUS_OBJ   = $(BONUS_SRC:.c=.o)

# HEADER      = libft.h

# #-----------#
# #|	RULES  |#
# #-----------#

# all: $(NAME)

# $(NAME): $(OBJ)
# 	$(AR) $(NAME) $(OBJ)

# bonus: $(OBJ) $(BONUS_OBJ)
# 	$(AR) $(NAME) $(OBJ) $(BONUS_OBJ)

# %.o: %.c $(HEADER)
# 	$(CC) $(CFLAGS) -c $< -o $@

# clean:
# 	rm -f $(OBJ) $(BONUS_OBJ)

# fclean: clean
# 	rm -f $(NAME)

# re: fclean all

# .PHONY: all clean fclean re bonus
